use assert_true/false instead of assert()
Otherwise the build fails with userspace-rcu 0.14 with

   error: implicit declaration of function 'assert' [-Werror=implicit-function-declaration]
   note: 'assert' is defined in header '<assert.h>'; did you forget to '#include <assert.h>'?