multipath-tools tests: suppress a compiler warning for vpd.c
The following warning has been observed with gcc 15.2.1 on Fedora Rawhide:

vpd.c: In function 'create_vpd83.constprop':
vpd.c:265:55: error: '%s' directive output truncated writing 64 bytes into a region of size 40 [-Werror=format-truncation=]
  265 |         len = snprintf((char *)(desc + 4), maxlen, "%s%s",
      |                                                       ^~
In file included from /usr/include/stdio.h:974,
                 from vpd.c:8:
In function 'snprintf',
    inlined from 'create_scsi_string_desc' at vpd.c:265:8,
    inlined from 'create_vpd83.constprop' at vpd.c:313:7:
/usr/include/bits/stdio2.h:68:10: note: '__builtin___snprintf_chk' output 65 or more bytes into a destination of size 40
   68 |   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   69 |                                    __glibc_objsize (__s), __fmt,
      |                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   70 |                                    __va_arg_pack ());
      |                                    ~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors

Fix it.

Signed-off-by: Martin Wilck <mwilck@suse.com>
(cherry picked from commit 888187ed1336cf6e938d625c59593661bb359882)
(cherry picked from commit 283b1c2a165432eecfd4fb67142d7a2304cf8626)
(cherry picked from commit e76073ea9dd2ddd590e9ba1843e66db16bb5c21f)