Add missing include <assert.h>
checkers.c: In function 'start_checker_thread':
checkers.c:392:9: error: implicit declaration of function 'assert' [-Werror=implicit-function-declaration]
  392 |         assert(ctx && ctx->cls && ctx->cls->thread);
      |         ^~~~~~
checkers.c:13:1: note: 'assert' is defined in header '<assert.h>'; did you forget to '#include <assert.h>'?

Signed-off-by: Sietse van Zanen <uglymotha@wizdom.nu>