multipath-tools tests: fix stringop-overflow build errors with gcc 11
gcc-11 throws an error compiling alias.c and dmevents.c:

In file included from ../libmultipath/checkers.h:4,
                 from ../libmultipath/prio.h:7,
                 from ../libmultipath/structs.h:8,
                 from dmevents.c:29:
../multipathd/dmevents.c: In function 'dmevent_loop':
../multipathd/dmevents.c:357:17: error: '__sigsetjmp' accessing 200 bytes in a region of size 72 [-Werror=stringop-overflow=]
  357 |                 pthread_cleanup_push(cleanup_lock, &waiter->vecs->lock);
      |                 ^~~~~~~~~~~~~~~~~~~~
../multipathd/dmevents.c:357:17: note: referencing argument 1 of type 'struct __jmp_buf_tag *'
/usr/include/pthread.h:734:12: note: in a call to function '__sigsetjmp'
  734 | extern int __sigsetjmp (struct __jmp_buf_tag *__env, int __savemask) __THROWNL;
      |            ^~~~~~~~~~~

The reason seems to be a mismatch between the __sigsetjmp() prototype
in <setjmp.h> and <pthread.h>. The error is encountered iUntil this is fixed in the toolchain,
work around it by including <pthread.h> before <setjmp.h>.